version: '3'
services:
  psycholess-site:
    build: .
    container_name: psycholess-site
    restart: always
    ports:
      - "3000:3000"

  nginx:
    image: nginx:mainline
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - psycholess-site
    restart: unless-stopped
