version: '3'
services:
  psycholess-backend:
    build: .
    container_name: psycholess-backend
    restart: always
    expose:
      - "3000"
    networks:
      - web_network

networks:
  web_network:
    external: true
