version: '3'
services:
  psycholess-site:
    build: .
    container_name: psycholess-site
    restart: always
    expose:
      - "3000"

  nginx:
    image: openquantumsafe/nginx-quic
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    depends_on:
      - psycholess-site
    restart: unless-stopped
