FROM nginx:mainline-alpine

# Install required packages for HTTP/3 (QUIC)
RUN apk add --no-cache \
    nginx-mod-http-geoip2 \
    nginx-mod-http-image-filter \
    nginx-mod-http-headers-more \
    nginx-mod-http-lua \
    nginx-mod-http-ndk \
    nginx-mod-http-perl \
    nginx-mod-http-xslt-filter \
    nginx-mod-mail \
    nginx-mod-stream \
    nginx-mod-stream-geoip2

CMD ["nginx", "-g", "daemon off;"]
